name: Workflow for Codeclimate example-php
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: 6954c1b338b6e59d7410d048d5e2af5eb3fcdf056a29775f8c8c08aea0e1fd84
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
      - name: Install dependencies
        run: composer self-update && composer install && composer dump-autoload
      - name: Code Climate Setup
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Run Tests
        run: |
          php vendor/bin/phpunit --coverage-clover --configuration phpunit.xml build/logs/clover.xml tests/
          ./cc-test-reporter after-build -t clover --exit-code $?